os:
  - linux
  - osx
  - windows

language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - RUSTFLAGS='-C target-feature=+crt-static'
  - RUSTFLAGS='-C target-feature=-crt-static'

script:
  - cargo test --all
